project_id = "jmotgyyubakklguttqca"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"

[functions.parse-desty-xlsx]
verify_jwt = false

[functions.process-sales-import]
verify_jwt = false

[functions.calculate-optimal-stock]
verify_jwt = false

[functions.apply-optimal-stock]
verify_jwt = false

[functions.run-tests]
verify_jwt = false

[functions.auto-journal-purchase]
verify_jwt = false

[functions.auto-journal-stock]
verify_jwt = false
